### ISSUE TITLE
Unsupported Codecs 6 of 0 in androidmediaencoder_jni.cc - Xiaomi Note Pro 3

### ISSUE THREAD

**Issue by sirwoetang** [voximplant/react-native-voximplant#10]
When starting a video call with a Xiaomi I get the following logs after crash:

`09-05 17:12:29.391 E/rtc     (32729): # Fatal error in ../../talk/app/webrtc/java/jni/androidmediaencoder_jni.cc, line 305
09-05 17:12:29.391 E/rtc     (32729): # Check failed: codec_settings->codecType == codecType_
09-05 17:12:29.391 E/rtc     (32729): # Unsupported codec 6 for 0
09-05 17:12:29.391 E/rtc     (32729): #
09-05 17:12:29.391 F/libc    (32729): Fatal signal 6 (SIGABRT), code -6 in tid 348 (Thread-321)
09-05 17:12:29.391 I/libc    (32729): Suppressing debuggerd output because prctl(PR_GET_DUMPABLE)==0
09-05 17:12:29.401 D/audio_hw_primary(  430): out_set_parameters: enter: usecase(1: low-latency-playback) kvpairs: routing=1
09-05 17:12:29.401 D/audio_hw_extn(  430): audio_extn_set_anc_parameters: anc_enabled:0
09-05 17:12:29.401 I/AudioFlinger(  430): setAppName(), name=[], active=[1]
09-05 17:12:29.411 D/audio_hw_primary(  430): start_output_stream: enter: stream(0xab33b9a0)usecase(1: low-latency-playback) devices(0x1)
09-05 17:12:29.411 D/audio_hw_primary(  430): select_devices: out_snd_device(1: handset) in_snd_device(0: )
09-05 17:12:29.411 I/msm8916_platform(  430): platform_check_and_set_codec_backend_cfg: Usecase bitwidth 16, samplerate 48000, backend_idx 0
09-05 17:12:29.411 I/msm8916_platform(  430): platform_check_codec_backend_cfg Codec selected backend: 0 current bit width: 16 and sample rate: 48000
09-05 17:12:29.411 W/msm8916_platform(  430): platform_check_codec_backend_cfg:Use default bw and sr for voice/voip calls 
09-05 17:12:29.411 D/msm8916_platform(  430): platform_check_codec_backend_cfg: resetting sample_rate back to default, backend_idx: 0
09-05 17:12:29.411 I/msm8916_platform(  430): platform_check_codec_backend_cfg Codec selected backend: 0 updated bit width: 16 and sample rate: 48000
09-05 17:12:29.411 D/hardware_info(  430): hw_info_append_hw_type : device_name = handset
09-05 17:12:29.411 I/soundtrigger(  430): audio_extn_sound_trigger_update_device_status: device 0x1 of type 0 for Event 1, with Raise=0
09-05 17:12:29.411 I/audio_hw_primary(  430): select_devices Selected apptype: 69937
09-05 17:12:29.411 D/soundtrigger(  430): audio_extn_sound_trigger_update_stream_status: uc_id 1 of type 0 for Event 3, with Raise=0
09-05 17:12:29.411 I/audio_hw_utils(  430): audio_extn_utils_send_app_type_cfg app_type 69937, acdb_dev_id 7, sample_rate 48000
09-05 17:12:29.411 D/ACDB-LOADER(  430): ACDB -> send_audio_cal, acdb_id = 7, path =  0
09-05 17:12:29.411 D/ACDB-LOADER(  430): ACDB -> send_asm_topology
09-05 17:12:29.411 D/ACDB-LOADER(  430): ACDB -> ACDB_CMD_GET_AUDPROC_STREAM_TOPOLOGY_ID
09-05 17:12:29.411 D/ACDB-LOADER(  430): ACDB -> send_adm_topology
09-05 17:12:29.411 D/ACDB-LOADER(  430): ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TOPOLOGY_ID
09-05 17:12:29.411 D/ACDB-LOADER(  430): ACDB -> send_audtable
09-05 17:12:29.411 D/ACDB-LOADER(  430): ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TABLE_SIZE
09-05 17:12:29.411 D/ACDB-LOADER(  430): ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TABLE
09-05 17:12:29.411 D/ACDB-LOADER(  430): ACDB -> AUDIO_SET_AUDPROC_CAL
09-05 17:12:29.411 D/ACDB-LOADER(  430): ACDB -> send_audvoltable
09-05 17:12:29.411 D/ACDB-LOADER(  430): ACDB -> ACDB_CMD_GET_AUDPROC_GAIN_DEP_STEP_TABLE
09-05 17:12:29.411 D/ACDB-LOADER(  430): ACDB -> AUDIO_SET_AUDPROC_VOL_CAL
09-05 17:12:29.411 D/ACDB-LOADER(  430): ACDB -> send_audstrmtable
09-05 17:12:29.411 D/ACDB-LOADER(  430): ACDB -> ACDB_CMD_GET_AUDPROC_STREAM_TABLE_V2
09-05 17:12:29.411 D/ACDB-LOADER(  430): ACDB -> audstrm_cal->cal_type.cal_data.cal_size = 32
09-05 17:12:29.411 D/ACDB-LOADER(  430): ACDB -> send_afe_cal
09-05 17:12:29.411 D/ACDB-LOADER(  430): ACDB -> send_afe_topology
09-05 17:12:29.411 D/ACDB-LOADER(  430): ACDB -> ACDB_CMD_GET_AFE_TOPOLOGY_ID
09-05 17:12:29.411 D/ACDB-LOADER(  430): ACDB -> GET_AFE_TOPOLOGY_ID for adcd_id 7, Topology Id 112fc
09-05 17:12:29.411 D/ACDB-LOADER(  430): ACDB -> ACDB_CMD_GET_AFE_COMMON_TABLE
09-05 17:12:29.411 D/        (  430): Failed to fetch the lookup information of the device 00000007 
09-05 17:12:29.411 E/ACDB-LOADER(  430): Error: ACDB AFE returned = -19
09-05 17:12:29.411 D/ACDB-LOADER(  430): ACDB -> AUDIO_SET_AFE_CAL
09-05 17:12:29.411 D/ACDB-LOADER(  430): ACDB -> send_hw_delay : acdb_id = 7 path = 0
09-05 17:12:29.411 D/ACDB-LOADER(  430): ACDB -> ACDB_AVSYNC_INFO: ACDB_CMD_GET_DEVICE_PROPERTY
09-05 17:12:29.411 D/audio_hw_primary(  430): select_devices: done
09-05 17:12:29.411 D/msm8916_platform(  430): platform_set_channel_map mixer_ctl_name:Playback Channel Map12
09-05 17:12:29.411 D/msm8916_platform(  430): platform_set_channel_map: set mapping(1 2 0 0 0 0 0 0) for channel:2
09-05 17:12:29.531 W/CameraService(  430): Disconnecting camera client 0xab5635f8 since the binder for it died (this pid 430)
09-05 17:12:29.531 I/WindowState( 1345): WIN DEATH: Window{2b688038 u0 `

Any ideas on how to get the right codecs?

**Comment by aylarov** [comment]
What version of Android is installed on the device?

**Comment by sirwoetang** [comment]
Android 5.1.1 MIUI 7.1

**Comment by aylarov** [comment]
We will upgrade the SDK early next week to solve the problem

**Comment by aylarov** [comment]
@sirwoetang  give https://github.com/voximplant/react-native-voximplant/commit/8e80c4f7cd300326ad73e3319b737e0aba33c97f a try , it should fix this problem
