### ISSUE TITLE
Problem with sound channel

### ISSUE THREAD

**Issue by SNWStaff** [voximplant/react-native-voximplant#100]
Hello !

I'm actually facing a weird issue, but I'm pretty sure it is from voximplant or maybe an incompatibility between voximplant et react-native-sound.

After a call, on android only, when I try to change sound with phone buttons, the sound channel is stuck on "Call" until I kill the app. It's a problem because when I play a sound from my app after a call, I need to display all channel sound to low the "Media" channel manually, instead of just pressing phone buttons.

I can't share my code, but maybe someone will have an idea about that...

Sincerely
Florient

**Comment by SNWStaff** [comment]
Update : I managed to make a native module to manage sound mode. But now, in some cases, when I play sound after method call was called, sound is played with no sound. Actually investigating the issue.

**Comment by YuliaGrigorieva** [comment]
Hello @SNWStaff ,

What version of the Voximplant React Native SDK do you use?

We had an issue with audio mode on android that was resolved in v1.13.0 (Voximplant Android SDK 2.14.1). 
Please ensure that you use the latest version.

Best regards,
Yulia Grigorieva

**Comment by SNWStaff** [comment]
Hello !

I managed to make a native function on android to manage mode and, with last version of RN VoxImplant, it works perfectly.
But now I face another issue, on IOS, it seems to have some conflicts with Sound module, I am unable to play sound as ringtone on IOS, then after the bug appears, the sound of app is totally broken, and I need to restart the app to make sound works again (until next call received, then sound will be broken again...). I think VoxImplant try to force permanently to switch to the channel volume before call was started. I have no problem when I send a call and play a sound as ringback. The problems appears only on IOS 13

Sincerely
Florient

**Comment by SNWStaff** [comment]
I managed it to have no more issue with VoxImplant.
I close the issue, last versions of RNVoxImplant fix the issue.

**Comment by vipulparmar1989** [comment]
@SNWStaff  How to you manage incoming call Ringtone?
