### ISSUE TITLE
Call to 

### ISSUE THREAD

**Issue by vipulparmar1989** [voximplant/react-native-voximplant#103]
always return "Call failed: Not Found". can you know the application to application call in which id or name used for the audio/video call.

**Comment by YuliaGrigorieva** [comment]
Hello @vipulparmar1989 ,

Please ensure that you have a VoxEngine scenario and routing settings for your Voximplant application in the [Voximplant Control Panel](https://manage.voximplant.com/auth).

Please take a look at [this tutorial](https://voximplant.com/blog/voximplant-p2p-video-chat).

Best regards,
Yulia Grigorieva

**Comment by vipulparmar1989** [comment]
Thanks you

**Comment by vipulparmar1989** [comment]
how to play Ringtone? Any idea?

**Comment by YuliaGrigorieva** [comment]
Hello @vipulparmar1989 ,

We are currently working on the API to play audio files and expect it will be available soon.

However, if you use CallKit for iOS, you should play the ringtone throught CallKit API.

Best regards,
Yulia Grigorieva
