### ISSUE TITLE
Voximplant.VideoStreamType is not exported

### ISSUE THREAD

**Issue by daniily000** [voximplant/react-native-voximplant#106]
Hello, Voximplant Team!

I started using new `type` property of `Voximplant.VideoStream`, but I fail using `Voximplant.VideoStreamType` enum.

It seems to me it is not exported if Voximplant.js file. Modifying it with  
```js
import {ClientState, CameraType, RenderScaleType, LogLevel, CallError, VideoCodec, RequestAudioFocusMode, VideoStreamType /* add here */ } from "./Enums";
```
and
```js
export {
    Client,
    Call,
    CallEvents,
    Endpoint,
    VideoStream,
    VideoView,
    EndpointEvents,
    ClientEvents,
    ClientState,
    CameraType,
    RenderScaleType,
    CallError,
    LogLevel,
    VideoCodec,
    RequestAudioFocusMode,
    Hardware,
    Messaging,
    VideoStreamType // here
};
```
resolves the issue. I could make a PR if you wish :)

**Comment by YuliaGrigorieva** [comment]
Hello @daniily000 ,

We have released Voximplant React Native SDK 1.16.0 with the fix provided.
It is now available via npm.

Best regards,
Yulia Grigorieva
