### ISSUE TITLE
Random ACL error

### ISSUE THREAD

**Issue by alex-evans123** [voximplant/react-native-voximplant#109]
Hi, 
I'm getting ACL error with code 12 randomly when I'm trying to get conversation by uuid of a login user, the error occurs randomly and sometimes runs the same function with success.

```
      var messanger = Voximplant.getMessenger()
            messanger.getConversation(uuid)
            .then(d=>{
                success(d)
                console.log(d)
            }).catch(e=>{
                 console.log(e)
            })
```
**Project Info** 

> react-native-voximplant version 1.17.0
> react-native : 0.61.5
> api level 29
> enableHermes : false
> xcode : 13.3.1
> ios : 13

**Device Info**

> Android : 
> Pixel 3, version:Android 10
> Emulator , version Android 10

> Ios : 
> Simulator iphone 8 plus, ios 13
> Hardware device iphone 7, ios 13

**Comment by alex-evans123** [comment]
Please answer, I have to update my client about it.

**Comment by YuliaGrigorieva** [comment]
Hello @alex-evans123 ,
Error code 12 (ACL error) means that the user does not have the access to this conversation. It may happen if the conversation is not public and/or this user is not in its participant list.

Please check that this conversation uuid is in the conversations list of this user ( User.conversationsList ) or this conversation is public ( Conversation.publicJoin )

Best regards,
Yulia Grigorieva

**Comment by alex-evans123** [comment]
@YuliaGrigorieva  I'm requesting a direct conversation, which was created between my loggedin user and other vox user

**Comment by alex-evans123** [comment]
@YuliaGrigorieva I have also tried createConversation ( with direct conversation configuration ) method and sometimes this method also fails with an ACL error

**Comment by alex-evans123** [comment]
Closing this issue, I was facing this issue because my connection with vox was getting timeout and is now fixed by adding event listener of disconnect.
Thank you
