### ISSUE TITLE
App crashed after call disconnected and video panel is hided

### ISSUE THREAD

**Issue by dseledtsov** [voximplant/react-native-voximplant#11]
After video call disconnect by other abonent and hiding component with VoxImplant.RemoteView and VoxImplant.Preview Android application crashed.

JNI DETECTED ERROR IN APPLICATION: JNI CallStaticVoidMethodV called with pending exception java.lang.NullPointerException: Attempt to read from field 'org.webrtc.VideoRenderer com.zingaya.voximplant.VoxImplantRendererInfo.renderer' on a null object reference
at void com.zingaya.voximplant.VoxImplantRenderer.internalRemoveRenderer(long) ((null):-1)

In demo app this exception throwed after call disconnect and unselect toggle button "Video"

[my-app-log.txt](https://github.com/voximplant/react-native-voximplant/files/475519/my-app-log.txt)
[react-native-demo-log.txt](https://github.com/voximplant/react-native-voximplant/files/475435/react-native-demo-log.txt)

**Comment by aylarov** [comment]
Fixed with https://github.com/voximplant/react-native-voximplant/commit/8e80c4f7cd300326ad73e3319b737e0aba33c97f
