### ISSUE TITLE
Force close app when build release apk with enableSeparateBuildPerCPUArchitecture and enableProguardInReleaseBuilds = true 

### ISSUE THREAD

**Issue by gandarain** [voximplant/react-native-voximplant#119]
I try to implement chat feature with voximplant in. my React Native app and I use react native voximplant sdk, for my project.
In debug mode, everything is fine. In release mode with set enableSeparateBuildPerCPUArchitecture and enableProguardInReleaseBuilds equal to false, everything is working fine too. But when I try to set enableSeparateBuildPerCPUArchitecture and enableProguardInReleaseBuilds equal to true. My react native app will force close.
I try to figure out, what happend and what fuction will make a force close app. And I found this

````
async loginVoximplant() {
    let clientConfig = {}
    let client = Voximplant.getInstance(clientConfig)
    try {
      await client.disconnect()
      let state = await client.getClientState()
      if (state === Voximplant.ClientState.DISCONNECTED) {
        await client.connect()
      }
      let authResult = await client.login(this.props.profile.voximplant_username, this.props.profile.voximplant_password)
      console.log('Response from login voximplant ', authResult)
      this.getTransactionChat(this.props.profile.type)
    } catch (e) {
      console.log('Error from login voximplant ', e)
    }
  }
````

I call this function in my component did mount, when I command this function, everything working fine with enableSeparateBuildPerCPUArchitecture and enableProguardInReleaseBuilds equal to true. I dont know why. Please give me an solution for this problem

**Comment by YuliaGrigorieva** [comment]
Hello @gandarain ,

I think the issue might be cause by enableProguardInReleaseBuilds = true and proguard strips some parts of the Voximplant native SDK.

Please add to the proguard rules the following:
```
-keep class org.webrtc.voiceengine.** {*;}
-keep class org.webrtc.** {*;}
-keepnames public class org.webrtc.voiceengine.** {*;}
-keepnames public class org.webrtc.** {*;}
-keepclasseswithmembernames class * { native <methods>; }

-keepclassmembers enum * {
    public static **[] values();    public static ** valueOf(java.lang.String);}

-keep public class com.zingaya.voximplant.* {
      public protected *;}

-keep public class com.voximplant.sdk.* {
      public protected *;}
```
and the rules from our dependencies:
https://github.com/google/gson/blob/master/examples/android-proguard-example/proguard.cfg
https://github.com/square/okhttp/blob/master/okhttp/src/main/resources/META-INF/proguard/okhttp3.pro

Please let me know the results.

Best regards,
Yulia Grigorieva

**Comment by gandarain** [comment]
Thanks for your answer, 
I have seen the link you sent. But I dont know , but I don't know where I will put the command from this link.
https://github.com/google/gson/blob/master/examples/android-proguard-example/proguard.cfg
https://github.com/square/okhttp/blob/master/okhttp/src/main/resources/META-INF/proguard/okhttp3.pro

Any idea, where I should put that command?
Thanks.

**Comment by YuliaGrigorieva** [comment]
You should have `proguard-rules.pro` file in your project located in `<your_project>/android/app` folder.

You need to put everything from these files and a snippet that I have provided in my previous comment to this file.

**Comment by gandarain** [comment]
Your solution is working, but now i get a new error from get conversation.
When debug mode, everything is working fine, but when relase mode and enableSeparateBuildPerCPUArchitecture and enableProguardInReleaseBuilds equal to true, I get an error in get conversation. 
The error code is 10002, description error is Response Timeout.
Any idea, how to fix this error?

**Comment by YuliaGrigorieva** [comment]
Hi @gandarain !

Is it 100% reproducible issue?

I need the SDK logs with getConversation response to understand what causes this issue.

Best regards,
Yulia Grigorieva

**Comment by gandarain** [comment]
Hi, thanks for reply this issue.
DId you mean this log?
<img src="https://user-images.githubusercontent.com/27923352/89027007-e7078f00-d353-11ea-9b01-298c0674930c.png" height="200" width="550"> <br/>

**Comment by YuliaGrigorieva** [comment]
No, I mean adb logcat logs (from Android Studio for example) with VOXSDK tag

**Comment by gandarain** [comment]
I am sorry, I dont understand what do you mean.
If you dont mind, can you explain to me, how to get adb logcat logs from android studio with VOXSDK tag, or you can provide that log by your self?
Thank for your reply.

**Comment by YuliaGrigorieva** [comment]
Hello @gandarain ,

Sorry for the delayed response.

Yes, I need these logs. However, could you please capture them starting a messaging API call, i.e. "getConversation" or any other you received an error.

Best regards,
Yulia Grigorieva
