### ISSUE TITLE
Problems with Incoming Voice IP Notifications on iOS

### ISSUE THREAD

**Issue by vorvex** [voximplant/react-native-voximplant#121]
Hello,

I have been struggling for over a week now trying to make the voximplant SDK work with our application. We are looking to receive incoming calls via our react-native app (no video needed), but are struggling when the app is closed.

When the App is active and the voximplant user is successfully connected no errors occur. However, when the User is not active in the app an incoming call will be received and displayed via the Delegate M Logic, but when the call is accepted, the App opens and no callId is being forwarded to my Call Screen.

`
// --- Handle incoming pushes (for ios >= 11)
- (void)pushRegistry:(PKPushRegistry *)registry 
didReceiveIncomingPushWithPayload:(PKPushPayload *)payload 
                          forType:(PKPushType)type 
            withCompletionHandler:(void (^)(void))completion {
  

  [RNVoipPushNotificationManager didReceiveIncomingPushWithPayload:payload forType:(NSString *)type];

  NSString *uuid = [VIClientModule uuidForPushNotification:payload.dictionaryPayload].UUIDString;
  
  // Commented this out since in some cases the Application is active but the User is not connected to the VI Cloud
  // if ([UIApplication sharedApplication].applicationState == UIApplicationStateActive) {
  //   NSLog(@"AppDelegate: didReceiveIncomingPush: application is in active state");
  // }

  
  if ([RNCallKeep isCallActive:uuid]){
    NSLog(@"AppDelegate: didReceiveIncomingPush: call is already been reported");
  }

    NSLog(@"AppDelegate: didReceiveIncomingPush: report new incoming call to CallKit");
    NSString *callerName = [[payload.dictionaryPayload valueForKey:@"voximplant"] valueForKey:@"display_name"];
    [RNCallKeep reportNewIncomingCall:uuid handle:callerName handleType:@"generic" hasVideo:NO 
   localizedCallerName:callerName fromPushKit:YES payload:payload.dictionaryPayload];

  completion();
}
`

After hours of problem-solving, I nailed the error down to the incomingCall Function in my CallManager.

When the App is opened by a VoIP-Notification this function will eventually get triggered but the event.call object that is included either is not being added correctly to the addCall Function or has no callID because I can neither get the Call by Id nor send the event.call.callId to the Call Screen.

`
  _incomingCall = event => {
    if (this.call !== null) {
      event.call.decline();
      return;
    }

    this.addCall(event.call);
    this.call.on(Voximplant.CallEvents.Disconnected, this._callDisconnected);
    if (Platform.OS === 'ios') {
      if (this.currentAppState === 'active') {

        this.callKitManager.showIncomingCall(
          false,
          event.call.getEndpoints()[0].displayName,
          event.call.callId,
          event.call.callKitUUID
        );
      } else {
        this.callKitManager.callKitUuid = event.call.callKitUUID;
        this.callKitManager.callId = event.call.callId;
        this.callKitManager.withVideo = false;

        Voximplant.Hardware.AudioDeviceManager.getInstance().callKitConfigureAudioSession();
        this.answer(); // This function is being used to accept the call If this.call is not null or otherwise send an Error

        NavigationService.navigate('Call', {
          callId: event.call.callId,
          isVideo: false,
          from: null,
          isIncoming: true
        });

        // this.answer();
      }
    } else {
      this._showIncomingScreenOrNotification(event);
    }
  };
`

I understand by now, that this function is getting triggered by the pushNotificationReceived that I add as an event listener on Login.

`
 pushNotificationReceived(notification) {
    (async () => {
      try {
        await this.loginWithToken();
        this.client.handlePushNotification(notification);
      } catch (error) {
        addElementToLog(
          'Error when receiving PushNotification: ' + error,
          'error'
        );
      }
    })();
  }
`

But I cannot find any reason why the call data is being lost on the way.

Thank you in advance for a fast answer,

Vorvex.

**Comment by YuliaGrigorieva** [comment]
Hello @vorvex !

The Call object provided by the IncomingCall event should be correct. I have checked that the callId is correctly filled, but could you please provide the SDK version you use to double check it?

You are right, if the client is not logged in and has received a push, the IncomingCall event is triggered only the client logs in and provide the push notification data to the sdk.

Your code looks ok except one thing. I'm not sure about the correctness of `this.answer()` call. I assume that this method invokes `Call.answer` API, but if the call is reported to the CallKit, you should wait its event that the user has answered the call from the CallKit UI and only after it answer the Voximplant call. Otherwise there can be an unexpected behavior for audio path, since CallKit also controls the AVAudioSession and the audio may fail to start correctly in this case.

Best regards,
Yulia Grigorieva

**Comment by vorvex** [comment]
Hello,

Thank you for you response! I made some changes according to your answer. And managed to got it to work now. I now see some inconsistencies while testing and I tracked them down to the pushNotiificationReceived function
`
  pushNotificationReceived(notification) {
    (async () => {
      try {
        await this.loginWithToken();
        this.client.handlePushNotification(notification);
      } catch (error) {
        alert('Error when receiving PushNotification: ' + error);
      }
    })();
  }
`

I get a lot of Connection Failed Errors when trying to loginWithToken this happens in around 30% of incoming calls especially when another app is opened. When this happens I receive an event in _incomingCall but with call as null is there any way to increase the redundancy in this?

Best,

Vorvex

**Comment by YuliaGrigorieva** [comment]
Hello @vorvex .

The behavior you describe is quite strange. If the SDK can't establish the connection to the Voximplant Cloud, you should not receive IncomingCall event.

I recommend you collect the logs for this case (from Xcode output with #VI/ tag) and send them to our support team (support@voximplant.com)

Best regards,
Yulia Grigorieva
