### ISSUE TITLE
Communication between multiple apps

### ISSUE THREAD

**Issue by rajngarg** [voximplant/react-native-voximplant#122]
Hi,
I am implementing voximplant in user and vendor apps and everything works great but having a problem of multiple apps communication. At first I tried to implement by creating a single application on voximplant that worked well but in this case I am not able to upload VoIP certificates for both apps inside single voximplant application as it accepts only one certificate.

Now I have created two different apps on voximplant and now I don't know how to communicate between them.
Please Help, Thanks.

**Comment by YuliaGrigorieva** [comment]
Hello @rajngarg 

As far as I understand your case, you need only one Voximplant application.
To upload mulitple push certificates to a Voximplant application, you can specify bundle id / package name of the application the certificate is genrated for:
![изображение](https://user-images.githubusercontent.com/8545374/94245439-eab62d00-ff22-11ea-9c65-d9c197b6b7f4.png)
After that you will need to specify bundle id/package name on SDK initialization by setting it to [ClientConfig.bundleId](https://voximplant.com/docs/references/reactnative/voximplant/clientconfig#bundleid) property. Please ensure that it is set correctly and match that one specified in the Voximplant Control Panel.

Best regards,
Yulia Grigorieva

**Comment by rajngarg** [comment]
Hello @YuliaGrigorieva ,
Thanks for your response and that worked well now I am having a problem with generating VoIP token. I am implementing it for the first time so having issues.
I have also checked logs.

{"sdk_type":"ios","token":null,"msg":"Push certificate not match to a bundle","result":false}

Please let me know why this error occurs.
Thanks

**Comment by rajngarg** [comment]
I am new to this so I don't know that it doesn't work on the simulator. When tried on the physical device works fine.
