### ISSUE TITLE
On adding 2nd voip certificate of vendor app voip notifications stopped

### ISSUE THREAD

**Issue by rajngarg** [voximplant/react-native-voximplant#125]
Hello, I am developing a customer-vendor app and when I add only customer side voip certificates in the voximplant panel then it is working good but when I add another voip certificate of vendor app all voip notifications stopped working on both apps. 

In call logs it is showing 
"Push certificate not match to a bundle"

Thanks in advance

**Comment by alex-evans123** [comment]
Hi @rajngarg , I think you need to use separate bundle id for both the certificates, i.e the bundle id which is required on certificates panel is not same as your app's bundle id and you should use separate bundle ids for both production and development ceritifcates.

For Example

I have certificates like this

com.example-prod for production certificate and
com.example-dev for development certificate

and inside code you have to add some kind of check use the correct bundle id for both cases

**Please note that I have answered this from my own experience and I do not represent the voximplant team :)**

Thank you.

**Comment by rajngarg** [comment]
Hi @alex-evans123 thanks for the reply

I am only working on development mode so I think I don't need to upload the production certificate yet.

My problem is that I have two different apps like the customer-vendor system if I only use a customer certificate then it is working fine on the customer side but when I upload vendor side certificate then VoIP notifications stop on the customer app also. I am using only development certificates.

**Comment by rajngarg** [comment]
Hello @alex-evans123 , Where we need to enter bundle ids inside the code?

**Comment by YuliaGrigorieva** [comment]
Hello @rajngarg ,

Please take a look at [ClientConfig.bundleId](https://voximplant.com/docs/references/reactnative/voximplant/clientconfig#bundleid) property.

Best regards,
Yulia Grigorieva

**Comment by rajngarg** [comment]
Thanks @YuliaGrigorieva , I am able to do it as you suggested with passing bundleId while initializing.

`Voximplant.getInstance({ bundleId: 'com.testapp' })`
