### ISSUE TITLE
Group Video Call

### ISSUE THREAD

**Issue by alex-evans123** [voximplant/react-native-voximplant#126]
Hi @YuliaGrigorieva 
I'm implementing video call using callConference but can not find any resources, group call should be like whatsApp or GoogleHangouts. Please point me to the right direction.

Problem I'm facing is CallConference creates a conference and others have to join it, it doesn't notify the other participant, I couldn't find anything that wants me to add a participant list to the conference, please help

**Comment by alex-evans123** [comment]
Any one here to help??

**Comment by alex-evans123** [comment]
Any one here to help??

@YuliaGrigorieva ??

**Comment by YuliaGrigorieva** [comment]
Hello @alex-evans123 ,

Do I understand correctly that you need the following case:
when a user starts a conference, other participants (that user has selected for this call) should receive IncomingCall event and should be able to join a call by answering it?

Best regards,
Yulia Grigorieva

**Comment by alex-evans123** [comment]
yes you are right

**Comment by YuliaGrigorieva** [comment]
Hello @alex-evans123 ,

All you need is to modify your VoxEngine scenario as it describes how the call should be processed.

I assume you have already read [this article](https://voximplant.com/docs/tutorials/video-conference-through-voximplant-media-servers) and setup a VoxEngine scenario for a video conference based on its `Step 4 - VoxEngine: set up Voximplant application with JS scenarios`

To implement your case you need to change this part of the code:
```
VoxEngine.addEventListener(AppEvents.CallAlerting, function (e) {
  e.call.answer();
  partsCounter = partsCounter + 1;
  const endpoint = conf.add({
    call: e.call,
    mode: "FORWARD",
    direction: "BOTH", scheme: e.scheme
  });
  Logger.write(`New endpoint was added ID: ${endpoint.id}`);
});
```
to the following one:
```
VoxEngine.addEventListener(AppEvents.CallAlerting, function (e) {
  e.call.answer();
  partsCounter = partsCounter + 1;
  const endpoint = conf.add({
    call: e.call,
    mode: "FORWARD",
    direction: "BOTH", scheme: e.scheme
  });

  Logger.write(`New endpoint was added ID: ${endpoint.id}`);

  function checkForTermination() {
    if (partsCounter === 0) {
     conf.stop();
     conf = null;
    }
  }

  function participantDisconnected() {
    partsCounter = partsCounter - 1;
    if (partsCounter === 0) {
      setTimeout(checkForTermination, 1000 * 10); // wait for 10 ceconds
    }
  }

  e.call.addEventListener(CallEvents.Disconnected, function (e) {
    participantDisconnected();
  });
  let user = e.customData;
  let callParticipant = VoxEngine.callUser(user, "myconf", "Conference call", {}, true);

  callParticipant.addEventListener(CallEvents.Connected, function(e) {
    endpointParticipant = conf.add({
      call: e.call,
      mode: "FORWARD",
      direction: "BOTH", scheme: e.scheme});
  });
  callParticipant.addEventListener(CallEvents.Disconnected, function(e) {
      participantDisconnected();
  });
});
```

Some notes and explanations:
1. the scenario gets Voximplant users names (participants) from the custom data in [AppEvents.CallAlerting](https://voximplant.com/docs/references/voxengine/appevents#callalerting) event handler. This event is invoked when you make an outgoing conference call from the SDK via Client.callConference("myconf", callSettings). The user names should be passed in [callSettings.customData](https://voximplant.com/docs/references/reactnative/voximplant/callsettings#customdata)
2. after it makes outgoing calls to call participants using CallUser method.
3. you need to subscribe to the [CallEvents.Connected](https://voximplant.com/docs/references/voxengine/callevents#connected) event to join the user to the conference call, when he answers the incoming call on the client.
4. you also need to subscribe to the [CallEvents.Disconnected](https://voximplant.com/docs/references/voxengine/callevents#disconnected) event to end the conference call when all endpoints have left the conference call.
5. the provided example demonstrates the approach with one user name passed via custom data, you can change it to handle multiple user names.

Best regards,
Yulia Grigorieva

**Comment by alex-evans123** [comment]
Thank you for the support.
