### ISSUE TITLE
Call voice issue in some specific cases

### ISSUE THREAD

**Issue by rajngarg** [voximplant/react-native-voximplant#127]
Hello, I am developing customer-vendor apps from the same account and having an issue related to voice.

everything works fine like connection and background calls but having issues in some cases I am not receiving call audio on the 2nd call. Please let me know how it works and which methods create these kinds of issues.

Thanks.

**Comment by YuliaGrigorieva** [comment]
Hello @rajngarg ,

Please provide more information about the issue. 

At least we need the steps to reproduce, reproducible rate, if the issue is reproducible with the demo project, what happens on the 1st call etc.

Best regards,
Yulia Grigorieva
