### ISSUE TITLE
Call sometimes interupts by itself after 30 seconds

### ISSUE THREAD

**Issue by Zvukamar** [voximplant/react-native-voximplant#128]
Hello,

Ill try to describe the case as much as possible.
Side A calls to side B by PSTN.
Side B answers the call, and the balance are enought for more than 5 minutes.
The call interupts after 30 seconds without side A or side B involved.

It does not always happen but it happen pretty frequently.
Any suggestion?
Thanks

**Comment by YuliaGrigorieva** [comment]
Hello @Zvukamar ,

The issue requires the analysis of the call session logs, your VoxEngine scenario and the balance. 

I suggest to contact our support team via support@voximplant.com or from the [Voximplant Control Panel](https://manage.voximplant.com/support/all) to keep sensitive information secure.

Best regards,
Yulia Grigorieva
