### ISSUE TITLE
"Payment required" issue occuring

### ISSUE THREAD

**Issue by RD1991** [voximplant/react-native-voximplant#13]
Hi There,
Thank you for awesome library. 
After building the react-native and web application I'm getting 'Payment required' error (Currently I'm using this for testing purpose) . But I'm not seeing any updates or documentation regarding payment. 
Can anyone out there guide me regarding this? 

Does zone matter anyhow ? Because I'm using services from India.

**Comment by aylarov** [comment]
Please check http://voximplant.com for the additional info, only p2p calls are free

**Comment by RD1991** [comment]
I'm checking for p2p calls only. 
What I did is , created application, users (2 user) and scenarios as described in above URL.
Then installed the react-native application on mobile devices. And from one user I called the another one.  

The caller was only able to listen 'pre-recording'. 
Can you please guide what's wrong I'm doing ?

**Comment by aylarov** [comment]
To make p2p call you need to have the right VoxEngine scenario and pass the right parameters in call function, check https://github.com/voximplant/react-native-demo , it has toggle button that activates p2p calling. For VoxEngine scenario check http://voximplant.com/blog/voximplant-p2p-video-chat/

**Comment by RD1991** [comment]
Hi @aylarov, 
Even if now I have paid account, i don't know why I still receive "Payment required" in header when installed on iPhone. 

Can you please respond over this ? 

![screen shot 2016-10-01 at 5 55 50 pm](https://cloud.githubusercontent.com/assets/16399313/19014045/7374bd94-8800-11e6-9b45-beb971ab8ba8.png)

**Comment by aylarov** [comment]
@RD1991 please send info to support [at] voximplant.com including your account name

**Comment by aylarov** [comment]
You have enabled "Separate account balance" for user, but haven't transferred fund to his account balance. Either disable it, or transfer some funds from voximplant account balance to user account balance. More of that, you have scenario for P2P calls, but looks like on client side you don't specify X-DirectCall header, that's why call goes via servers and require funds.
