### ISSUE TITLE
Flow related queries

### ISSUE THREAD

**Issue by alex-evans123** [voximplant/react-native-voximplant#130]
Hi @YuliaGrigorieva can you please answer a few more flow related queries?

**1. How to get filtered events ?**
- I want to show the number of sendMessage events 
- Currently the problem is with the sendMessage event Im also getting edit and create events which is messing up with the read counts

**2. How check if the callee is busy on another call ?**
- Currently there is no default way of getting status of the user
- How would you transmit the user status -  offline or busy

**3. How to decline call from native side ?**
- Currently Im using react-native-callkit for showing the incoming call when the app is in background or killed state
- Call accept is working perfectly but the problem is when user declines the call from native call screen (callkit) I couldn't find a way to transmit that event to the js side to deliver the event
- If the user doesn't respond to the call i.e neither accept nor decline, the callkit screen remains on, for this there should be call drop notification or something to inform the call drop on the native side.

It would be really helpful if you could come up with the answers to all these questions.

Thank you

**Comment by YuliaGrigorieva** [comment]
Hello @alex-evans123 ,

1. How to get filtered events ?
Voximplant does not provide the API to filter events. Each event (of message/conversation events) has its sequence number that allows to get all history of this conversation. The read status can be applied to any event, not only messages.
2. How check if the callee is busy on another call ?
You can use [User.customData](https://voximplant.com/docs/references/reactnative/voximplant/messaging/user#customdata) API that allows to set any data (status, for example) and get it on other users clients. To monitor the User changes, you can subscribe to this user using [Messenger.subscribe](https://voximplant.com/docs/references/reactnative/voximplant/messaging/messenger#subscribe) API. When a user changes its custom data, other user will receive [MessengerEvents.EditUser](https://voximplant.com/docs/references/reactnative/voximplant/messaging/messengereventtypes#edituser) event.
This approach allows to set any custom status.
3. How to decline call from native side ?
You should not decline the call on native side using react-native. Neigher react-native-voximplant nor react-native-callkeep supports it.
The correct way to handle call decline from CallKit UI is to handle the event in JS code. 
Some recommendations that may be helpful:
- initialize the classe(s) that manage RNCallKeep API on application start in JS code and subscribe to all events
- RNCallKeep should invoke [RNCallKeepPerformEndCallAction](https://github.com/react-native-webrtc/react-native-callkeep/blob/c3ade440bb19ef27d6b8a6a410defd69032c2e34/ios/RNCallKeep/RNCallKeep.m#L706) event when a user declines a call
- then call Voximplant [Call.hangup](https://voximplant.com/docs/references/reactnative/voximplant/call#hangup) / [Call.decline](https://voximplant.com/docs/references/reactnative/voximplant/call#decline) / [Call.reject](https://voximplant.com/docs/references/reactnative/voximplant/call#reject) API after you received an incoming call event from Voximplant SDK
- if a user declined a call before you received an incoming call event, store this action any suitable way and call Voximplant API as mentioned before
- as soon as you have received a push notification and obtain a push payload in the JS code, connect and log in a user to the Voximplant Cloud even if a user has already declined a call. 
- if a user has not responded to a call (neither accept nor decline), you should receive a [CallEvents.Disconnected](https://voximplant.com/docs/references/reactnative/voximplant/calleventtypes#disconnected) event. Voximplant has a timeout for 40-60 seconds to respond to a call, so you should receive this event if you are connected and logged in to the Voximplant Cloud. Once you receive this event, call [RNCallKepp.endCall](https://github.com/react-native-webrtc/react-native-callkeep/blob/c3ade440bb19ef27d6b8a6a410defd69032c2e34/index.js#L156) API to remove CallKit incoming call screen from the phone screen.

Hope this helps. Please let me know if you have any questions or face any issues.

Best regards,
Yulia Grigorieva
