### ISSUE TITLE
Queue behavior is missing

### ISSUE THREAD

**Issue by bilalbaraz** [voximplant/react-native-voximplant#131]
Cannot change operator ACD Status on RN App. If you would like to use queue system for your operators by using react native app, forget change status. So operators that use react native app can log in but cannot update ACD status to be available for incoming calls. That behavior is missing on this package. Available for Web SDK.
FYI.

**Comment by YuliaGrigorieva** [comment]
Hello @bilalbaraz ,

This functionality is currently not available in mobile SDK and is not planned to be added.

Best regards,
Yulia Grigorieva
