### ISSUE TITLE
VIMessagingModule.java: package android.support.annotation does not exist

### ISSUE THREAD

**Issue by alexanderoskin** [voximplant/react-native-voximplant#139]
`
/node_modules/react-native-voximplant/android/src/main/java/com/voximplant/reactnative/VIMessagingModule.java:7: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
`

react: 17.0.2
react-native: 0.66.4
react-native-voximplant: 1.27.1

**Comment by pe1ros** [comment]
Hello @alexanderoskin !

Could you please provide the following information:

1. Are android.useAndroidX and android.enableJetifier enabled in your Project->android->gradle.properties file?
2. How do you build your android app (from Android Studio/npx command/other)?

**Comment by alexanderoskin** [comment]
@pe1ros 

1. Yes, both enabled
2. Android Studio

**Comment by pe1ros** [comment]
Hello @alexanderoskin,

It seems the build failure is related to the issue with jetifier process while building the android app.
Please check the Android gradle plugin version is 4.0.0 or higher in android -> build.gradle file

For example:
```
dependencies {
        	classpath 'com.android.tools.build:gradle:4.2.2’
```

**Comment by alexanderoskin** [comment]
Hi @pe1ros 

Gradle plugin version is already 4.2.2. So that's not the problem.
