### ISSUE TITLE
iOS - Camera Not Working

### ISSUE THREAD

**Issue by basanthalluri** [voximplant/react-native-voximplant#15]
I was able to connect from mobile to mobile and mobile to web. I can hear the voice in both devices. But i can't see the video in both the iPhone devices.

iPhone 6, iOS 9.3 version.
React Native - 0.30

You can view the screenshot below.
![blackscreen](https://cloud.githubusercontent.com/assets/1677959/18878427/5e405826-8485-11e6-9ab3-640d5e0de00e.jpg)

Please suggest me.

**Comment by aylarov** [comment]
Hi, please set camera resolution using setCameraResolution function
`VoxImplant.SDK.setCameraResolution(480, 640);`
