### ISSUE TITLE
Problems with incoming calls

### ISSUE THREAD

**Issue by alexanderoskin** [voximplant/react-native-voximplant#153]
We are struggling to make the Voximplant SDK work with our application. Problems with incoming voice calls. Not video. Video call we are not tested.

- Outgoing calls in out app are working perfectly.
- If we use CallApp from [react-native-demo](https://github.com/voximplant/react-native-demo) repo incoming calls with our Voxengine scenario are working perfectly
- When we implement CallApp principle in our app for incoming calls they are not working.

What's going on with incoming call:
- Call received by app successfully.
- We can answer or decline to the call. Answer and decline are handled successfully.
- Call established successfully when we answer incoming call.
- When incoming call established callee didn't hear caller, caller didn't hear calee
- But call record successfully andщт the call record we only hear caller and no callee.

**Comment by alexanderoskin** [comment]
Upgrading react-native-voximplant from 1.29.1 to 1.31.0 in demo CallApp [react-native-demo](https://github.com/voximplant/react-native-demo) and incoming calls are stoped to work as in our main app too.

**Comment by alexanderoskin** [comment]
Downgraded react-native-voximplant from 1.31.0 to 1.30.0 and everything is working perfectly. So to reproduce the issue you can upgrade react-native-voximplant from 1.29.1 to 1.31.0 in the demo CallApp [react-native-demo](https://github.com/voximplant/react-native-demo).

**Comment by pe1ros** [comment]
Hello @alexanderoskin !

Thank you for reaching out to us!

We have found the root cause of the issue and have just released Voximplant React Native SDK 1.32.0 with the fix.

Please update to the new version and let us know if the issue is still reproducible.

**Comment by alexanderoskin** [comment]
@pe1ros yep, tested and everything work now. But we still experience this issue https://github.com/voximplant/react-native-voximplant/issues/155 that blocked our app to use in production. Any thoughts?
