### ISSUE TITLE
Call.Failed when app in background/killed

### ISSUE THREAD

**Issue by alexanderoskin** [voximplant/react-native-voximplant#155]
Incoming calls works fine when app is running in foreground, call screen shows. Outgoing calls works fine, too.

But if we minimize the app though we got interesting behavior both in background and killed app states. When we make a call then incoming call is dropped with `Sent event to JS onPhoneEvent with params [{code = 404 ; headers = {Reason =  ; } ; id = UX0ED73sTpWMoeFVtL8ROcj2G8ynsER1oTYrfmoLD7s ; name = Call.Failed ; reason = Not Found ; } ;  ]`. After the call is dropped call screen is appear on a phone. If we answer the call all app sdk methods called, sdk establish connection, sdk login and fire `call disconnected` event as incoming call was dropped early.

Sometimes incoming call works fine. About 1 of 20-25 calls work as excepted.

Not tested on Android, only iOS.

I have read Callkeep, VIOP push and Voximpant docs over a million times and nothing helped.

**Comment by pe1ros** [comment]
Hello @alexanderoskin !

We have found possible root of you problem and a workaround for it. Can you enter Voximplant Panel => Push certificates, and do three things:
1. Re-upload you certificate, check it’s not expired.
2. Delete all other expired certificates for your app. You may check expiration date in keychain -> certificates -> expiration date
3. If you have more then 1 Apple_Voip push certificate, please check you are using the correct bundle id when you initialize Voximplant Client .

**Comment by alexanderoskin** [comment]
@pe1ros as there was no answer I've wrote to the customer support. The issue was on your side and it was resoled. Thank you.
