### ISSUE TITLE
App Crashing when not giving  permissions

### ISSUE THREAD

**Issue by swaroopa94** [voximplant/react-native-voximplant#16]
Hi,
While Iam running in android my app get crashed.
when i run my app its showing an error like "android.permission.RECORD_AUDIO" when i on the permissions in the setting its running fine. at line 35 in voxImplemetModule.java (this.client.setAndroidContext(reactContext, true, true);)

So for android version >6.0 we have to give run time permission so due to this when i initially run my app its geeting crashed when i kept the runtime permissions it showing every permission three times.

can  you help in solving this problem

Thanks

**Comment by YuliaGrigorieva** [comment]
Permissions are set per-app by developer. Please follow the tutorial on how it can be done
