### ISSUE TITLE
Autolinking broken in 0.69

### ISSUE THREAD

**Issue by alexanderoskin** [voximplant/react-native-voximplant#164]
Due to https://github.com/react-native-community/cli/pull/1537 some things in your react-native.config.js have been deprecated and removed, thus failing autolinking schema validation (for example dependency.platforms.ios.podspecPath).

Steps to Reproduce

Create a vanilla RN project with latest 0.69.1 with npx react-native init Example.
Add this package.
Observe it not being autolinked.

**Comment by pe1ros** [comment]
Hello @alexanderoskin 

We released new version v1.34.0 with fix this issue, please update your project  to latest react-native-voximplant version.
