### ISSUE TITLE
ios/Pods/VoxImplantSDK/VoxImplant.framework/VoxImplant' does not contain bitcode.

### ISSUE THREAD

**Issue by Harsha-Sampath** [voximplant/react-native-voximplant#169]
Hi,
After the implementation react native VoxImplant SDK project is working properly. 
but when I try to archive the project it failed.

This message is showing.

'/Users/macbook/Projects/MedLankaApp/MedlankaCustomerProject/MedlankaCustomer/ios/Pods/VoxImplantSDK/VoxImplant.framework/VoxImplant' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/macbook/Projects/MedLankaApp/MedlankaCustomerProject/MedlankaCustomer/ios/Pods/VoxImplantSDK/VoxImplant.framework/VoxImplant' for architecture arm64

I tried 
Xcode ==> setting ==>  ENABLE_BITCODE (Yes/No)

Please give me a solution regarding the above matter.

**Comment by pe1ros** [comment]
Hello @Harsha-Sampath !

 To enable bitcode in your project, you need to do the following steps:
 
 1. Enable Bitcode on Xcode Proect->Build Options->Enable Bitcode.
 2. Download a required Voximplant iOS SDK version (and VoximplantWebRTC dependency) with bitcode for a specific 
     Voximplant React Native SDK. Please check [this page](https://voximplant.com/docs/howtos/sdks/bitcode) for download links. Voximplant React Native SDK 1.34.0 depends on [VoxImplant_bitcode(2.46.9)](https://s3.eu-central-1.amazonaws.com/voximplant-releases/ios-sdk/2.46.9/VoxImplant_bitcode.zip)  and [VoxImplantWebRTC_bitcode(93.0.0)](https://s3.eu-central-1.amazonaws.com/voximplant-releases/ios-webrtc/93.0.0/VoxImplantWebRTC_bitcode.zip)
3. Update Podfile
target ‘ProjectName’ do 
		// add these lines
		pod ‘VoxImplantSDK’, :path => ‘Path/To/VoxImplant_bitcode/’
		pod ‘VoxImplantWebRTC’, :path => ‘Path/To/VoxImplantWebRTC_bitcode/’
4. Run ```pod install``` command from YourProejct/ios folder



If you want disable bitcode in your project:
1. Update your Podfile like this
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```
2. Run ```pod install``` command from YourProejct/ios folder

**Comment by Harsha-Sampath** [comment]
I fixed that issue, thank you for your support.
