### ISSUE TITLE
ConnectionEstablished is not fired

### ISSUE THREAD

**Issue by wilmxre** [voximplant/react-native-voximplant#179]
After my phone goes in background mode (i open a different app for example) the ConnectionClosed event is fired. When i open the app again, the ConnectionEstablished and AuthResult events are triggered.
My app functions as intended like this, but after i have a call and go in background mode and go back to foreground state the ConnectionEstablished and AuthResult events are not fired anymore. What could possible cause this?

OS: iOS
Device: iPhone XS Max

**Comment by ryancha89** [comment]
I have struggled for a week for this problem too
when loginWithToken you should put node argument when you trigger connect function
await this.client.connect({ node: 'node1' });
