### ISSUE TITLE
Build Failing out of the Box for iOS 10 | Xcode 8

### ISSUE THREAD

**Issue by frostfat** [voximplant/react-native-voximplant#18]
Assuming this needs an update to account for recent iOS updates. Any input on resolving this would be appreciated :)

<img width="904" alt="screen shot 2016-10-18 at 18 58 24" src="https://cloud.githubusercontent.com/assets/6690161/19487955/28eb14c2-9565-11e6-842d-860a33912b05.png">

[Build RNSinch_2016-10-18T18-49-51.txt](https://github.com/voximplant/react-native-voximplant/files/536901/Build.RNSinch_2016-10-18T18-49-51.txt)

**Comment by aylarov** [comment]
It looks like you haven't added Voximplant library to your project

**Comment by frostfat** [comment]
Hey thanks, simple fix.
