### ISSUE TITLE
Introduce ConnectionNode enum?

### ISSUE THREAD

**Issue by alexanderoskin** [voximplant/react-native-voximplant#183]
`Introduce ConnectionNode enum` and `ConnectOptions.node is a required parameter to establish the connection with the Voximplant Cloud`. What is `node`? Where it can be found? To what node our Voximplant account belongs to? How we can find this? Where we can find the docs?

**Comment by YuliaGrigorieva** [comment]
Hello!

You can find the information and the code example in this article: https://voximplant.com/docs/getting-started/platform/react-native#connect-to-the-voximplant-cloud-and-log-in

Sorry for the inconvenience, we will update the readme file and improve our documentation asap.

Best regards,
Yulia Grigorieva

**Comment by alexanderoskin** [comment]
> Hello!
> 
> You can find the information and the code example in this article: https://voximplant.com/docs/getting-started/platform/react-native#connect-to-the-voximplant-cloud-and-log-in
> 
> Sorry for the inconvenience, we will update the readme file and improve our documentation asap.
> 
> Best regards, Yulia Grigorieva

Thank you!

**Comment by taniaprocha** [comment]
I still do not understand which node I should choose. How can I find which node my account uses?
