### ISSUE TITLE
Login Failure When Connected to VPN

### ISSUE THREAD

**Issue by robbiemoore** [voximplant/react-native-voximplant#20]
Hi, I've got this integrated and it works a charm. However when I'm connected to a VPN on my iPhone, and try to make a call, voice I can't hear anything on either end. Is this a known issue? I'm going to look deeper into it next week but seems like an odd one.

**Comment by robbiemoore** [comment]
I'm still having issues with this. When connected to VPN, I cannot login, and therefore cannot make calls. Any suggestions on debugging, or insight as to what the problem may be?

**Comment by grigoryvp** [comment]
Voice use UDP packets. You need to ensure that your VPN software can send UDP packets
