### ISSUE TITLE
App crash on VoxImplant.SDK.connect

### ISSUE THREAD

**Issue by anishtr4** [voximplant/react-native-voximplant#27]
I have installed the demo app in my I phone 6 with IOS 10.3.1, But when the following function eixcue the application crash VoxImplant.SDK.connect. 

It is working perfectly fine in IOS 9.X devices.

**Comment by grigoryvp** [comment]
In order to troubleshoot the problem we need a crash report or, at least, a stacktrace. Is it possible for you to create one and attach to this ticket?

**Comment by grigoryvp** [comment]
We have updated the demo project install instructions. Can you please check the new version?
