### ISSUE TITLE
WebSDK Error when calling on Firefox

### ISSUE THREAD

**Issue by knightsoftware** [voximplant/react-native-voximplant#28]
On newest Firefox (normal or ESR) I keep getting error message: NS_ERROR_UNEXPECTED

RTCPeerConnection()adapter.debug.js (row 544)
t()voximplant.min.js (row 6)
n()voximplant.min.js (row 1)
VoxImplant</g</e.prototype.setupDirectPC()voximplant.min.js (row 2)
value()voximplant.min.js (row 1)
VoxImplant</S</e.prototype.call()voximplant.min.js (row 2)
value()voximplant.min.js (row 1)
VoxImplant</E</e.prototype.call()voximplant.min.js (row 1)
value()

The error does not appear when using old, legacy WebSDK API, just on the EDGE version

**Comment by YuliaGrigorieva** [comment]
Voximplant Web SDK and Voximplant React Native SDK are completely different things. If you wish to report some issue with Web SDK, feel free contact us via support@voximplant.com
