### ISSUE TITLE
Video is not showing sometime (peer to peer)

### ISSUE THREAD

**Issue by anishtr4** [voximplant/react-native-voximplant#30]
When I am using web application to connect to my mobile app(peer to peer). Sometimes the video not showing in mobile and web but the call is getting connected properly. Please let me know if there is any solution.

Also please do let me know fi there is any way to call without peer to peer from Websdk to mobile.app.

**Comment by anishtr4** [comment]
@grigoryvp  any solution ?. We are planning to use it in our commercial product if you guys can give a proper solution for this.

**Comment by YuliaGrigorieva** [comment]
The issue should be fixed with the latest SDK update. Please check and reopen if needed
