### ISSUE TITLE
Create user along with login option

### ISSUE THREAD

**Issue by aryaminus** [voximplant/react-native-voximplant#31]
I already have a login+sign up system in my project with firebase but for voximplant I again have to login. Anyway that the new created user can be pushed in voximplant under an Application?

**Comment by anishtr4** [comment]
@aryaminus  You need to create a service on your  backend . Which will do the Voximplant registration once you got successful registration on your firebase.

**Comment by aryaminus** [comment]
I have implemented it using _Asyncstorage_ and interacting with _fetch_ and _response_ . But was searching for alternative way

**Comment by grigoryvp** [comment]
Hello!

That's a correct way. Our cloud can be fully controlled via HTTP API, and creating Voximplant user for each of your own users is a correct 1-to-1 mapping
