### ISSUE TITLE
headers not forwarded to incoming call

### ISSUE THREAD

**Issue by izaa** [voximplant/react-native-voximplant#36]
related: https://github.com/voximplant/react-native-voximplant/issues/22

I have the latest version of this package. I'm using android version.

I start the call
```
 const headers = {
 'X-user': userId,
};
VoxImplant.SDK.startCall(callId,headers);
```

I see the headers in VoxImplant Control Panel:

> 
> 2018-04-12 07:26:39 Sent event to JS onPhoneEvent with params [{callerid = removed;  customData =  ;  destination = destid ;  displayName =dname ;  fromURI = sip:caller@app.acc.voximplant.com ;  headers = {VI-Authenticated-Caller = removed;  VI-Browser = voxmobile ;  VI-CallData =  ;  VI-Client-Device = WebRTC ;  VI-Client-IP = 45.181.240.244 ;  VI-Client-Type = user ;  VI-ClientVersion = 2.3.6 ;  **X-user = destid;**   ;  } ;  id = ae19d51f6e35f53c.1523517999.122496 ;  name = Application.CallAlerting ;  scheme = {"" : {"audio" : [{"direction" : "sendrecv" , "flows" : [{"cname" : "PEnHLL+ETYK0URy7" , "ssrc" : 2217349308}] , "msid" : "LCnDgpb2lzj6pMV4XK5QJTfDeGFLO9GIR71S cc033994-dea3-4582-840f-a9db4ded969f" , "uniq" : 0}] , "place" : 0 , "type" : "" , "video" : [{"codecs" : [104,124] , "direction" : "sendrecv" , "flows" : [{"cname" : "PEnHLL+ETYK0URy7" , "ssrc" : 3905939635}] , "msid" : "LCnDgpb2lzj6pMV4XK5QJTfDeGFLO9GIR71S fd7371c7-059c-45f4-8119-b8acdfb8e86a" , "uniq" : 0}]}} ;  toURI = sip:destid@app.acc.voximplant.com ;  } ;  ]
> 2018-04-12 07:26:39 Executing JS command: EnableMediaStatistics with params [{id = ae19d51f6e35f53c.1523517999.122496 ;  } ;  ]

But the incomingcall contains no headers:

![image](https://user-images.githubusercontent.com/3491506/38662472-1509ae0a-3e3d-11e8-89f9-5ffd45f42ad6.png)

Anu suggestion what to do? Thanks!

**Comment by YuliaGrigorieva** [comment]
Hello!

The issue may be related to the scenario that you use in Voximplant Control Panel for this call.

In case if you use "forwardCallToUser" or "forwardCallToUserDirect" in the scenario, the headers should be provided in the IncomingCall event, otherwise you should implement the logic to pass the headers between calls in your scenario.

Best regards,
Yulia Grigorieva

**Comment by izaa** [comment]
Hi,

thanks for the hint. If I understand your docs correctly, the forwardCallToUser does not forward headers to the easyProcess method. I have to try:

from: https://voximplant.com/docs/references/appengine/VoxEngine.html

**callUser**
`VoxEngine.callUser(username, callerid, displayName, extraHeaders, video, scheme)`

**forwardCallToUser**
```
VoxEngine.addEventListener(AppEvents.CallAlerting, function (e) {
    var newCall = VoxEngine.callUser(e.destination, e.callerid, e.displayName);
    VoxEngine.easyProcess(e.call, newCall);
  }
 
// so the method could do the same job
VoxEngine.forwardCallToUser();
```

**Comment by izaa** [comment]
So, because headers don't work, how should I forward some data trough call from caller to recipient? Can I change the displayname or how to use CustomData? Any help would be appreciated! 

Thank you!

**Comment by irbisadm** [comment]
Hi. 
Can you send the link to VoxEngine server log into my email isheko@voximplant.com?
Your scenario must transceive headers, so it is strange. Can you use the sendMessage function as a temporary workaround?

**Comment by izaa** [comment]
Hi @irbisadm

I'll send you the log file. But i got it working using` e.headers` instead of `e.extraHeaders ` I found out the correct field using our VoxEngine debugger. Creat tool :)

```
VoxEngine.addEventListener(AppEvents.CallAlerting, function (e) {
    var newCall = VoxEngine.callUser(e.destination, e.callerid, e.displayName, **e.headers**, true);
    VoxEngine.easyProcess(e.call, newCall);
});
 
```

**Comment by irbisadm** [comment]
Yep, sure!
![image](https://user-images.githubusercontent.com/575439/38675796-a19be3fa-3e61-11e8-907d-db587327facd.png)

**Comment by izaa** [comment]
Yes my misunderstanding from here. Sorry about that :)

![image](https://user-images.githubusercontent.com/3491506/38676416-9cf1ade2-3e63-11e8-8cf2-b923ed7e3752.png)
