### ISSUE TITLE
undefined is not an object (VoxImplantModule.init)

### ISSUE THREAD

**Issue by david-dss** [voximplant/react-native-voximplant#37]
I am using the latest library.

I've follow all installation steps, however I encounter an error in iOS where `VoxImplant.SDK.init` fails.
The code is running fine in Android. So, I guess there is a problem with iOS installation.

In the 7th step of the iOS installation, it is said that there should not be any `.xcodeproj` file in `Library` folder. However, I use other libraries that generate that file. Is this what caused the issue? If yes, is there any way to fix it?

**Comment by YuliaGrigorieva** [comment]
Hello!

We support only cocoapods instalation approach for Voximplant React Native iOS SDK.

In case of other libraries/modules dependencies, please check if they contain **.podspec** files that can be included to your project Podfile.

If your other dependencies do not support cocoapods, you can create the **.podspec** files yourself using cocoapods documentation and existing podspecs as a reference.

For example, in our demo project we use several third-party react-native modules that are integrated via this [podspec](https://github.com/voximplant/react-native-demo/blob/822c740f2d67d48aea5ad15a1895bf6c0f1879a1/ios/Podfile#L73-L76)

Best regards,
Yulia Grigorieva

**Comment by izaa** [comment]
@YuliaGrigorieva this really is an issue now. I have compiled my iOS project from scratch coulple of hundreds time and solving different issues. App opens fine without VOXImplant, but If vox installed, it gives this error.

in react-native-voximplant/index.js the NativeModules is empty, could that be the reason?
