### ISSUE TITLE
Installation without Cocoapods

### ISSUE THREAD

**Issue by emin93** [voximplant/react-native-voximplant#38]
First of all: Thank you for this great module. I enjoy using it a lot.

During the setup I didn't find a way to install the dependency without using Cocoapods. I wonder if it's possible as that's default when installing dependencies on a new React Native project. (https://facebook.github.io/react-native/docs/linking-libraries-ios.html)

This would also enable "react-native link" to link dependencies automatically.

For Android it worked perfectly:
```
emin93$: react-native link react-native-voximplant
Scanning folders for symlinks in /Users/emin93/Documents/Projects/Demo/node_modules (20ms)
rnpm-install info Linking react-native-voximplant android dependency
rnpm-install info Platform 'android' module react-native-voximplant has been successfully linked
```

Thanks in common.

**Comment by tmjordan** [comment]
It would be nice, if we can have an altenative to cocoapods, such as a manual linking.
I have another problem, i can't use "use_frameworks" in my podfile because of my other pods. So i can't use voximplant in ios. Please help.

**Comment by YuliaGrigorieva** [comment]
Hello!

We will remove use_frameworks! requirement for iOS installation in the next Voximplant React Native SDK release. However we do not plan to support non-cocoapods installation in the near future.

I will update the issue once we publish a new release.

Best regards,
Yulia Grigorieva

**Comment by YuliaGrigorieva** [comment]
Voximplant React Native SDK 1.6.0 was released on April 5th.

With this release we have removed CocoaLumberjack dependency and made `use_frameworks!` optional. These changes should resolve integration issues with other libraries.

However, we support the Voximplant React Native SDK integration only via cocoapods. 

Closing this issue for now.
