### ISSUE TITLE
React.createClass is not working

### ISSUE THREAD

**Issue by chetnadaffodil** [voximplant/react-native-voximplant#4]
Seems you're trying to access 'ReactNative.createClass' from the 'react-native' package. Perhaps you meant to access 'React.createClass' from the 'react' package instead?

For example, instead of:

  import React, { Component, View } from 'react-native';

You should now do:

  import React, { Component } from 'react';
  import { View } from 'react-native';

Check the release notes on how to upgrade your code - https://github.com/facebook/react-native/releases/tag/v0.25.1
handleException @ ExceptionsManager.js:55handleError @ InitializeJavaScriptAppEngine.js:136reportFatalError @ error-guard.js:30guardedLoadModule @ require.js:60_require @ require.js:49(anonymous function) @ require-0.js:1messageHandlers.executeApplicationScript @ debuggerWorker.js:18onmessage @ debuggerWorker.js:33
ExceptionsManager.js:55 Module AppRegistry is not a registered callable module.handleException @ ExceptionsManager.js:55handleError @ InitializeJavaScriptAppEngine.js:136reportFatalError @ error-guard.js:30guard @ MessageQueue.js:43callFunctionReturnFlushedQueue @ MessageQueue.js:92onmessage @ debuggerWorker.js:39

**Please update your your package according to react native version v0.29 as React.createClass is not supported in react-native package any longer. It throws an runtime every single time. I have tried on my own but it doesn't seem to work fine.
Please update your example as well for the same version.**

![screenshot from 2016-07-14 18 05 02](https://cloud.githubusercontent.com/assets/17562095/16839678/f53eccee-49ed-11e6-9738-454f4f164ae3.png)

**Comment by aylarov** [comment]
Fixed with https://github.com/voximplant/react-native-voximplant/commit/b3d5085391da56aa8ca811c55cd9fb122cd76e3c
