### ISSUE TITLE
Android studio 3

### ISSUE THREAD

**Issue by alican-k** [voximplant/react-native-voximplant#48]
Hi there, 

With Android Studio 3, I had to replace `compile project(':react-native-voximplant') `  in the `android/app/build.gradle` file with `implementation 'com.voximplant:voximplant-sdk:2.5.4'`

Now, I am not able to import `VoxImplantReactPackage` in MainApplication.java

Is there anyone used react-native-voximplant with android strudio 3 ?

**Comment by YuliaGrigorieva** [comment]
Hello!

There is no need for the replacement you described.

Voximplant React Native SDK is built atop of our native SDKs.
`implementation 'com.voximplant:voximplant-sdk:2.5.4'` - this line integrates Voximplant Android SDK and is already a part of our React Native SDK: https://github.com/voximplant/react-native-voximplant/blob/14a7f89b4b01e3fe74cbe046a0f33a6ae68ca67d/android/build.gradle#L36

In your `android/app/build.gradle` file you should add `react-native-voximplant` as a dependency (but not `com.voximplant:voximplant-sdk`) :
```
implementation project(':react-native-voximplant')
```

Please ensure that you have followed the installation instructions for Android:
https://github.com/voximplant/react-native-voximplant#manual-install-1

We also have a demo project that already has Voximplant React Native SDK integrated. You can build and run it on your environment:
https://github.com/voximplant/react-native-demo

Best regards,
Yulia Grigorieva

**Comment by alican-k** [comment]
It is solved Yulia, thanks for your help!
