### ISSUE TITLE
Cannot call dev menu

### ISSUE THREAD

**Issue by wayne1203** [voximplant/react-native-voximplant#49]
Hi, I follow the guide on official website to build the app including voximplant library
Finally, I using the Podfile in "voximplant/react-native-demo" but I can't call dev menu if "use_frameworks!" enable.

Here is my environment:
>   React Native Environment Info:
>     System:
>       OS: macOS High Sierra 10.13.6
>       CPU: x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
>       Memory: 676.20 MB / 16.00 GB
>       Shell: 3.2.57 - /bin/bash
>     Binaries:
>       Node: 10.13.0 - /usr/local/bin/node
>       Yarn: 1.12.1 - /usr/local/bin/yarn
>       npm: 6.4.1 - /usr/local/bin/npm
>       Watchman: 4.9.0 - /usr/local/bin/watchman
>     SDKs:
>       iOS SDK:
>         Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
>     IDEs:
>       Android Studio: 3.2 AI-181.5540.7.32.5056338
>       Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
>     npmPackages:
>       react: 16.6.0-alpha.8af6728 => 16.6.0-alpha.8af6728 
>       react-native: 0.57.4 => 0.57.4 
>     npmGlobalPackages:
>       react-native-cli: 2.0.1

**Comment by YuliaGrigorieva** [comment]
Hello!

Thank you for reaching out!

The issue may happen if the React is included twice.
Please ensure that you have removed all react *.xcodeproj from `Libraries` group in your Xcode project. 

Please also try calling dev menu in our demo application and let us know if the issue is reproducible on it with your environment.

Best regards,
Yulia Grigorieva

**Comment by wayne1203** [comment]
Hi,
Thank you for your suggestion and I tried to build the demo app.
But weird the Package Server (Metro Bundler) didn't start automatically so I run "react-native start/ npm start" after "react-native run-ios". Unfortunately the app still show "No bundle URL present"
<img width="1029" alt="2018-11-06 6 35 27" src="https://user-images.githubusercontent.com/8578341/48059014-feebc680-e1f2-11e8-8acf-c9b963b5e994.png">

**Comment by YuliaGrigorieva** [comment]
Hello!

Please try the following way:
1. run `react-native start` from the project root folder in terminal
2. open `VoximplantDemo.xcworkspace` file in Xcode (generated after `pod install` command run)
3. run and build the project from Xcode

Please let me know the results.

Best regards,
Yulia Grigorieva

**Comment by wayne1203** [comment]
Thanks @YuliaGrigorieva , the demo app is work now.
But is it have any problem if the Package Server not open in new Terminal automatically?

**Comment by YuliaGrigorieva** [comment]
Hello!

In case if the Packager server is not opened in terminal automatically, it won't work as the Packager Server is required.

Thant's why we recommend to start it separately before running the application.

Best regards, 
Yulia Grigorieva
