### ISSUE TITLE
Build failed on IOS

### ISSUE THREAD

**Issue by Linoa65** [voximplant/react-native-voximplant#53]
Hello !

I have problem to build my project for IOS. I just ran "pod install" to get all my modules and when I try to build I get this following errors on Xcode :

<img width="287" alt="capture d ecran 2018-12-19 a 12 59 35" src="https://user-images.githubusercontent.com/17029084/50218969-f956d400-038d-11e9-8d8e-24e0569c5806.png">

I tried to go back to a stable state, but each time, even if it works, when I run my "pod install" I get back these errors. Its a problem because even if it works for me before I run "pod install", other developers will get errors after running "pod install". I have clearly no idea to how to fix that. I follow each steps to link library, and I try all solutions given on github issues, but I won't modify module code, it's a bad practice and the problem will appears for others developers that haven't modify the module.

**Comment by YuliaGrigorieva** [comment]
Hello!

According to the screenshot, the issue is caused by double definition of React interfaces. 
Could you please check that you removed all React `*.xcodeproj` files from `Libraries` section in your Xcode project? 

If the React `*.xcodeproj` files are removed from `Libraries` section, please check the error output, it should show the paths for duplicated React interfaces. Analysis of these paths should point where React interfaces are double included.

Best regards,
Yulia Grigorieva

**Comment by Linoa65** [comment]
Hello,

Thanks for your answer, I removed all libraries .xcodeproj, but I get the same stack error.

Stack trace on react-native run-ios
`In file included from /Users/florientferrao/IdeaProjects/sweetnewworld_mvp_front/node_modules/react-native-voximplant/ios/VIClientModule.m:8:
/Users/florientferrao/IdeaProjects/sweetnewworld_mvp_front/node_modules/react-native/React/Base/RCTBridgeModule.h:63:11: warning: duplicate protocol definition of 'RCTBridgeModule' is ignored [-Wduplicate-protocol]
@protocol RCTBridgeModule <NSObject>
          ^
In module 'React' imported from /Users/florientferrao/IdeaProjects/sweetnewworld_mvp_front/node_modules/react-native/React/Base/RCTBridgeModule.h:10:
/Users/florientferrao/IdeaProjects/sweetnewworld_mvp_front/ios/build/Build/Products/Debug-iphonesimulator/React/React.framework/Headers/RCTBridgeModule.h:63:11: note: previous definition is here
@protocol RCTBridgeModule <NSObject>
          ^
In file included from /Users/florientferrao/IdeaProjects/sweetnewworld_mvp_front/node_modules/react-native-voximplant/ios/VIClientModule.m:9:
/Users/florientferrao/IdeaProjects/sweetnewworld_mvp_front/node_modules/react-native/React/Base/RCTConvert.h:25:1: error: duplicate interface definition for class 'RCTConvert'
@interface RCTConvert : NSObject
^
In module 'React' imported from /Users/florientferrao/IdeaProjects/sweetnewworld_mvp_front/node_modules/react-native/React/Base/RCTBridgeModule.h:10:
/Users/florientferrao/IdeaProjects/sweetnewworld_mvp_front/ios/build/Build/Products/Debug-iphonesimulator/React/React.framework/Headers/RCTConvert.h:25:12: note: previous definition is here
@interface RCTConvert : NSObject
           ^
In file included from /Users/florientferrao/IdeaProjects/sweetnewworld_mvp_front/node_modules/react-native-voximplant/ios/VIClientModule.m:9:
/Users/florientferrao/IdeaProjects/sweetnewworld_mvp_front/node_modules/react-native/React/Base/RCTConvert.h:135:12: error: definition of 'RCTConvert' must be imported from module 'React.RCTConvert' before it is required
@interface RCTConvert (Deprecated)
           ^
In module 'React' imported from /Users/florientferrao/IdeaProjects/sweetnewworld_mvp_front/node_modules/react-native/React/Base/RCTBridgeModule.h:10:
/Users/florientferrao/IdeaProjects/sweetnewworld_mvp_front/ios/build/Build/Products/Debug-iphonesimulator/React/React.framework/Headers/RCTConvert.h:25:12: note: previous definition is here
@interface RCTConvert : NSObject
           ^
In file included from /Users/florientferrao/IdeaProjects/sweetnewworld_mvp_front/node_modules/react-native-voximplant/ios/VIClientModule.m:9:
/Users/florientferrao/IdeaProjects/sweetnewworld_mvp_front/node_modules/react-native/React/Base/RCTConvert.h:135:24: warning: duplicate definition of category 'Deprecated' on interface 'RCTConvert'
@interface RCTConvert (Deprecated)
                       ^
In module 'React' imported from /Users/florientferrao/IdeaProjects/sweetnewworld_mvp_front/node_modules/react-native/React/Base/RCTBridgeModule.h:10:
/Users/florientferrao/IdeaProjects/sweetnewworld_mvp_front/ios/build/Build/Products/Debug-iphonesimulator/React/React.framework/Headers/RCTConvert.h:135:12: note: previous definition is here
@interface RCTConvert (Deprecated)
           ^
In file included from /Users/florientferrao/IdeaProjects/sweetnewworld_mvp_front/node_modules/react-native-voximplant/ios/VIClientModule.m:10:
In file included from /Users/florientferrao/IdeaProjects/sweetnewworld_mvp_front/node_modules/react-native-voximplant/ios/VIClientModule.h:9:
/Users/florientferrao/IdeaProjects/sweetnewworld_mvp_front/node_modules/react-native/React/Modules/RCTEventEmitter.h:14:1: error: duplicate interface definition for class 'RCTEventEmitter'
@interface RCTEventEmitter : NSObject <RCTBridgeModule>
^
In module 'React' imported from /Users/florientferrao/IdeaProjects/sweetnewworld_mvp_front/node_modules/react-native/React/Base/RCTBridgeModule.h:10:
/Users/florientferrao/IdeaProjects/sweetnewworld_mvp_front/ios/build/Build/Products/Debug-iphonesimulator/React/React.framework/Headers/RCTEventEmitter.h:14:12: note: previous definition is here
@interface RCTEventEmitter : NSObject <RCTBridgeModule>
           ^
In file included from /Users/florientferrao/IdeaProjects/sweetnewworld_mvp_front/node_modules/react-native-voximplant/ios/VIClientModule.m:10:
In file included from /Users/florientferrao/IdeaProjects/sweetnewworld_mvp_front/node_modules/react-native-voximplant/ios/VIClientModule.h:9:
/Users/florientferrao/IdeaProjects/sweetnewworld_mvp_front/node_modules/react-native/React/Modules/RCTEventEmitter.h:16:40: error: property has a previous declaration
@property (nonatomic, weak) RCTBridge *bridge;
                                       ^
In module 'React' imported from /Users/florientferrao/IdeaProjects/sweetnewworld_mvp_front/node_modules/react-native/React/Base/RCTBridgeModule.h:10:
/Users/florientferrao/IdeaProjects/sweetnewworld_mvp_front/ios/build/Build/Products/Debug-iphonesimulator/React/React.framework/Headers/RCTEventEmitter.h:16:40: note: property declared here
@property (nonatomic, weak) RCTBridge *bridge;
                                       ^
In file included from /Users/florientferrao/IdeaProjects/sweetnewworld_mvp_front/node_modules/react-native-voximplant/ios/VIClientModule.m:10:
/Users/florientferrao/IdeaProjects/sweetnewworld_mvp_front/node_modules/react-native-voximplant/ios/VIClientModule.h:12:29: error: definition of 'RCTEventEmitter' must be imported from module 'React.RCTEventEmitter' before it is required
@interface VIClientModule : RCTEventEmitter <RCTBridgeModule, VIClientSessionDelegate, VIClientCallManagerDelegate>
                            ^
In module 'React' imported from /Users/florientferrao/IdeaProjects/sweetnewworld_mvp_front/node_modules/react-native/React/Base/RCTBridgeModule.h:10:
/Users/florientferrao/IdeaProjects/sweetnewworld_mvp_front/ios/build/Build/Products/Debug-iphonesimulator/React/React.framework/Headers/RCTEventEmitter.h:14:12: note: previous definition is here
@interface RCTEventEmitter : NSObject <RCTBridgeModule>
`

**Comment by YuliaGrigorieva** [comment]
Hello!

Thank you for provided information!

Could you please also provide the information about the versions of:
1. react-native
2. react-native-voximplant

Have you tried to build [our demo application](https://github.com/voximplant/react-native-demo) on ios? Do you observe these issues while building the demo app?

Best regards,
Yulia Grigorieva

**Comment by Linoa65** [comment]
"react-native": "0.57.4"
"react-native-voximplant": "1.2.0"

Thanks :)

**Comment by Linoa65** [comment]
I didn't try to build the demo app. Last month I stopped to try to build IOS because I have not a developper account for now, so some feature are disabled. I'm just trying to make it build, because last month I correctly build it with vox implant.

**Comment by Linoa65** [comment]
I tried to downgrade my React Native version to 0.57.3 but still the same error. Tell me if you need my .pbxproj or anything necessary to help.

Best regard,
Florient

**Comment by YuliaGrigorieva** [comment]
Hello!

It would be helpful, if you could provide a sample project where I can reproduce the issue.

Best regards,
Yulia Grigorieva

**Comment by Linoa65** [comment]
I try some things, I comment "use_framework" in my Podfile

```# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'sweetnewworld_mvp_front' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for sweetnewworld_mvp_front
  pod 'Firebase/Core', '~> 5.9.0'
  pod 'Firebase/Auth', '~> 5.9.0'
  pod 'Firebase/Database', '~> 5.9.0'
  pod 'Firebase/Firestore', '~> 5.9.0'
  pod 'Firebase/Messaging', '~> 5.9.0'
  pod 'GoogleAppMeasurement', '~> 5.2.0'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/GLog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'React', :path => ‘../node_modules/react-native', :subspecs => [
      'Core',
      'RCTActionSheet',
      'RCTAnimation',
      'RCTGeolocation',
      'RCTImage',
      'RCTLinkingIOS',
      'RCTNetwork',
      'RCTSettings',
      'RCTText',
      'RCTVibration',
      'RCTWebSocket',
      'DevSupport',
      'CxxBridge'
      # Add any other subspecs you want to use in your project
  ]

  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'
  pod 'react-native-voximplant', :path => '../node_modules/react-native-voximplant'
  pod 'react-native-camera', :path => '../node_modules/react-native-camera'
  pod 'react-native-document-picker', :path => '../node_modules/react-native-document-picker'
  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'
  pod 'RNFS', :path => '../node_modules/react-native-fs'
  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
```

I verified there is no Libs in my Xcode project, no libraries linked in Xcode, all with Cocoapods, and now the VoxImplant lib successfully builds. But now I get this following error : 

```Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_RCTReconnectingWebSocket", referenced from:
      objc-class-ref in libReact.a(RCTPackagerConnection.o)
  "_OBJC_CLASS_$_RCTSRWebSocket", referenced from:
      objc-class-ref in libReact.a(RCTInspectorPackagerConnection.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by Linoa65** [comment]
Finally, I just remove the post_install in my Podfile, then link libReact.a to "Link binary with libraries" dependencies and my project successfully build. 

Thanks a lot for the help !

Best regards,
Florient
