### ISSUE TITLE
Support for video calls on iOS

### ISSUE THREAD

**Issue by MRDjeko** [voximplant/react-native-voximplant#54]
Yulia, thank you for this great module.
Did i get it right, there is no support for video calls on iOS?
Docs state that clientConfig.enableVideo = true is an Android only option.
So basically on iOS devices i can see the remote video stream, but cannot send the local video stream back?

**Comment by YuliaGrigorieva** [comment]
Hello!

Thank you for reaching out!

Video calls are supported for both Android and iOS platforms. Voximplant React Native SDK supports on both platforms:
- video send 
- video receive
- multiple video calls
- video conferences
- enable/disable video send during the call
- hold / unhold calls
- other functionality

ClientConfig.enableVideo is the option to enable/disable video functionality in sdk on android, by default video functionality is enabled. On iOS platform it is impossible to disable video functionality, so it is always enabled.

Please let me know if you have any questions or you run into any issues.

Best regards,
Yulia Grigorieva

**Comment by MRDjeko** [comment]
Thank you!
