### ISSUE TITLE
Bitcode support (iOS)

### ISSUE THREAD

**Issue by sanjaypojo** [voximplant/react-native-voximplant#58]
Hi, is there an easy way to get the library to work with bitcode? If not, then is there a way to disable bitcode only for voximplant in my podfile?

**Comment by YuliaGrigorieva** [comment]
Hello, @sanjaypojo !

You can't disable bitcode for your application dependencies selectively. So bitcode should be enabled for all components or disabled at all.

Voximplant iOS SDK (on which Voximplant React Native SDK for iOS is based on) is available on cocoapods without bitcode. It means if you install Voximplant React Native SDK according the steps provided in README file, you install Voximplant SDK with disabled bitcode.

If you need to use bitcode in your project, you can download the version of the Voximplant iOS SDK with bitcode and manually add it to the Podfile.
1. Visit https://voximplant.com/docs/references/iossdk/bitcode and download/unzip the version of the Voximplant iOS SDK required. Check the release notes of Voximplant React Native SDK to determine which version of the Voximplant iOS SDK you need: https://github.com/voximplant/react-native-voximplant/releases
2. Open your application Podfile and add the following lines with correct paths to downloaded frameworks. Please note you should keep the line with 'react-native-voximplant' pod:
```
    pod 'react-native-voximplant', path: '../node_modules/react-native-voximplant'

    // Add these lines
    pod 'VoxImplantSDK', path: '../Path/To/VoxImplant_bitcode/'
    pod 'VoxImplantWebRTC', path: '../Path/To/VoxImplantWebRTC_bitcode/'
```

Best regards,
Yulia Grigorieva

**Comment by sanjaypojo** [comment]
Thanks @YuliaGrigorieva, that makes sense!
