### ISSUE TITLE
Messaging: missing timestamp in retransmitEvent

### ISSUE THREAD

**Issue by ruscoder** [voximplant/react-native-voximplant#60]
Hello! 

I use RetransmitEvents for fetching messages history. And there is no timestamp in the event's result. 

```
[{sequence: 4, messengerEventType: "SendMessage", message: {…}, userId: "****", messengerAction: "sendMessage"}]
```

Maybe RetransmitEvents shouldn't be used for messages history? What the right way to implement it?

**Comment by YuliaGrigorieva** [comment]
Hello!

Thank you for reporting the issue!

RetrasmitEvents is the API to get the conversation history, so you did use it correctly. 
I checked and the timestamp is missing, so I will update the code to fix it.

I will let you know as soon as I commit the changes.

Best regards,
Yulia Grigorieva
