### ISSUE TITLE
Warning: Native component for "RCTVoxImplantRendererView" does not exist + Cannot read property 'closeConnection' of undefined

### ISSUE THREAD

**Issue by chetnadaffodil** [voximplant/react-native-voximplant#7]
![screenshot from 2016-07-18 13 42 28](https://cloud.githubusercontent.com/assets/17562095/16910233/2a1821ae-4cf5-11e6-9df2-5e2cf9161f3c.png)

**Comment by RD1991** [comment]
Got rid of this error by doing -> rnpm link react-native-voximplant

**Comment by aylarov** [comment]
As @RD1991 mentioned it's related to adding the library to the project, maybe rnpm still has some issues, but if you follow the manual instructions it should work well.
