### ISSUE TITLE
Choose a different default audio device

### ISSUE THREAD

**Issue by sanjaypojo** [voximplant/react-native-voximplant#70]
Currently, the audio device defaults to `EARPIECE`, but we'd like it to default to `SPEAKER`. We have a workaround to change the audio device once the call is connected. But it would be nice to be able to set this upfront. If we currently set the audio device when there are no calls, it interferes with background music playback from other apps etc.

**Comment by YuliaGrigorieva** [comment]
Hello!

Thank you for the feature request, I will discuss it with my team.

Currently our AudioDeviceManager is designed to be used to manage audio devices during the call, it should not affect audio settings if there are no calls at the moment.
Audio device selection logic is specific on each platform and also depends on audio device connected such as bluetouth or wired headset.

> If we currently set the audio device when there are no calls, it interferes with background music playback from other apps etc.

Could you please provide more details about this issue? What platform do you observe the issue? Could you please provide exact steps to reproduce the issue:
- what should be launched first: a background music playback or the app
- do you observe the issue if the app is launched when music is playing
- do you observe any issues if music starts to play from another app after the application launch / or changing the device via AudioDeviceManager

Best regards,
Yulia Grigorieva

**Comment by sanjaypojo** [comment]
Hi @YuliaGrigorieva, here are the details you requested:

Platform:  iOS

Replicate using the following steps:
(1) Play a song on Spotify. Connect bluetooth headphones and start listening.
(2) In your app, set the audio device to speaker on load (even though no call is made)

The music will start dropping and reconnecting continuously.

**Comment by YuliaGrigorieva** [comment]
Hello!

Thank you for the provided steps. Could you please also let me know:
- the version of Voximplant React Native SDK you use
- do you establish the connection to the Voximplant Cloud on the application load
- do you use connectivity check option to establish the connection to the Voximplant Cloud (https://voximplant.com/docs/references/reactnative/voximplant/connectoptions)

Best regards,
Yulia Grigorieva

**Comment by sanjaypojo** [comment]
Sure, here are the details:

- Version of react-native-voximplant: “1.4.0”
- Yes, we establish a connection on application load to receive calls as we don’t have push notifications yet
- No, we do not use connectivity check

**Comment by YuliaGrigorieva** [comment]
Hello, @sanjaypojo!

Unfortunately, I was not able to reproduce the issue on our demo application with the scenario provided.

Could you please confirm that you are able to reproduce it with the demo app? If so, could you please contact us at support@voximplant.com and provide Voximplant SDK logs from Xcode output?

Best regards,
Yulia Grigorieva
