### ISSUE TITLE
Native Module cannot be null

### ISSUE THREAD

**Issue by ozanmanav** [voximplant/react-native-voximplant#72]
I have a same problem like #42 . I tried these things but i'm getting this error again.

![image](https://user-images.githubusercontent.com/19241756/53503074-6be7dc80-3ac0-11e9-961b-e8b9ae037fc9.png)

My Repo : https://github.com/ozanmanav/voxTest2

Is there any idea for this ?

**Comment by YuliaGrigorieva** [comment]
Hello!

Please remove the references to all .xcodeproj in `Libraries` section:
<img width="288" alt="screenshot 2019-02-27 at 18 55 04" src="https://user-images.githubusercontent.com/8545374/53503812-dfd6b480-3ac1-11e9-8e84-3e51f211eedb.png">

Select them all -> right click on mouse -> "Delete" -> "Remove references"
Then please clean the project and build again.

Best regards,
Yulia Grigorieva

**Comment by ozanmanav** [comment]
Thanks @YuliaGrigorieva. Fixed.
