### ISSUE TITLE
Recovering data from the audio stream during a call

### ISSUE THREAD

**Issue by Woodhartt** [voximplant/react-native-voximplant#75]
Hello, using the react-native-voximplant module I would like to be able to retrieve the data from the audio stream during a call in order to be able to apply a transformation on it and return this modified data to the recipient. Is there a method to retrieve this data and return it later?
Thank you in advance for your answers.

**Comment by YuliaGrigorieva** [comment]
Hello!

Thank you for reaching out to us!

Unfortunately, it is currently possible only via Voximplant Web SDK.

Best regards,
Yulia Grigorieva

**Comment by Woodhartt** [comment]
Thank you for your answer.

I would like to know if this feature will be integrated in the other SDKs? And are there any examples of using the Web SDK with a webview?

Thank you for your help.

**Comment by YuliaGrigorieva** [comment]
Hello!

We plan this feature for this year for Android and iOS SDK, but I can't provide any release date.

Regarding Web SDK examples, please contact us at support@voximplant.com.

Best regards,
Yulia Grigorieva
