### ISSUE TITLE
library not found for -lVoxImplantSDK

### ISSUE THREAD

**Issue by shaikhussian** [voximplant/react-native-voximplant#8]
hai when i run this in xcode i got an error like this 
![callerror](https://cloud.githubusercontent.com/assets/11956308/17096158/ba2b4214-5275-11e6-9fde-4b3a5f8a42a9.png)
Even i import this file is from node-modules/react-native-voximplant/ios/VoxImplantSDK/lib/libVoxImplantSDK.a
please give me suggestions that how to resolve this problem

**Comment by aylarov** [comment]
You haven't added the path to the library to Library Search Path in Build Settings

**Comment by shaikhussian** [comment]
@aylarov thank you for responsding i added the library to LIbrary Search paths in Build settings but the errors are like this 
![1](https://cloud.githubusercontent.com/assets/11956308/17096825/e1de4092-5278-11e6-877b-5a4700d6440d.png)
![2](https://cloud.githubusercontent.com/assets/11956308/17096832/ec73612c-5278-11e6-9038-dc8b4ab3b26c.png)
![3](https://cloud.githubusercontent.com/assets/11956308/17096845/f6a5cfea-5278-11e6-9628-ed3004c59106.png)
in library Search i added like this
![path](https://cloud.githubusercontent.com/assets/11956308/17096877/0da52ab0-5279-11e6-8c70-2ccd96044c46.png)
can please tell that is there any error in path

**Comment by aylarov** [comment]
Have you added VideoToolbox.framework?

**Comment by shaikhussian** [comment]
where in xcode project path

**Comment by aylarov** [comment]
> In XCode, in the project navigator, select your project. Add libvoximplant.a, react-native-voximplant/VoxImplantSDK/libVoxImplantSDK.a, libc++.dylib or libc++.tbd, GLKit.framework and VideoToolbox.framework to your project's Build Phases ➜ Link Binary With Libraries

**Comment by shaikhussian** [comment]
@aylarov  thanks for the help now it working but i want to test it for that how can i login, please give me suggestions

**Comment by shaikhussian** [comment]
@aylarov when i try to run it in device this was the error
![screen shot 2016-07-25 at 6 37 03 pm](https://cloud.githubusercontent.com/assets/11956308/17102380/e99992be-5296-11e6-9608-635711080657.png)

**Comment by shaikhussian** [comment]
@aylarov do you have a chance to look at the error message?

**Comment by allright** [comment]
Please disable bitcode
![2016-07-26_17-34-30](https://cloud.githubusercontent.com/assets/374572/17142046/a288ab98-535f-11e6-9c3f-e67d924a96c0.png)

**Comment by shaikhussian** [comment]
@allright @aylarov i create an account in https://manage.voximplant.com but when i try to login app i unable to login, Is there any code i need to add when click on login i wrote some alert in index.ios.js
```
 _login(accnameValue, appnameValue, usernameValue, passwordValue) {
    alert("called:"+usernameValue +
      "@" + appnameValue +
      "." + accnameValue +
      ".voximplant.com", passwordValue)
    VoxImplant.SDK.login(usernameValue +
      "@" + appnameValue +
      "." + accnameValue +
      ".voximplant.com", passwordValue);
  }
```
i got the alert with the data i given but i am unable login into the app
please tell me that how can login, i there any code i need to add in after click on login
