### ISSUE TITLE
VoxImplant answerCall Issue

### ISSUE THREAD

**Issue by Ashish121** [voximplant/react-native-voximplant#84]
Hi,
I am getting issue related to Voximplant answerCall method.When I am opening a project with Xcode and building ,I am getting build error with message : - **No visible @interface for 'VoxImplant' declares the selector 'answerCall:withHeaders:'**.Kindly help me to fix this issue.

**Comment by YuliaGrigorieva** [comment]
Hello @Ashish121 ,

Could you please provide the version of the Voximplant React Native SDK you use?

Do you observe this issue in the demo project or in your own?

Please also let me know if you've followed integration steps for iOS platform and run `pod install` command.

Best regards,
Yulia Grigorieva

**Comment by Ashish121** [comment]
I am using  **react-native-voximplant: "^0.1.7"**.All basic steps are done and It was working perfectly few days ago.

**Comment by Ashish121** [comment]
![voximplant_error](https://user-images.githubusercontent.com/11734668/60580267-6964fe80-9da2-11e9-8fc0-b4d834893a40.png)

**Comment by YuliaGrigorieva** [comment]
Hello @Ashish121 ,

You are using a very old version of the Voximplant React Native SDK and deprecated APIs.
Please update to the latest version (1.8.0) and follow the integrations steps.

Also you can use [this migartion guide](https://voximplant.com/docs/references/reactnative/migration-guide) to easily move to the new APIs.

Best regards,
Yulia Grigorieva
