### ISSUE TITLE
[android] can't make build because of webrtc duplicate

### ISSUE THREAD

**Issue by alexei-sevrukov-topx** [voximplant/react-native-voximplant#89]
Good day. I'm stack on the problem with android build. When I add react-native-voximplant to android I get error
`Error: Program type already present: org.webrtc.Camera1Capturer`
Any idea about this error?

**Comment by YuliaGrigorieva** [comment]
Hello @alexei-sevrukov-topx ,

Please provide your project dependencies, most likely there is a conflict with another dependency.

Best regards,
Yulia Grigorieva

**Comment by alexei-sevrukov-topx** [comment]
@YuliaGrigorieva 
`"dependencies": {
    "@react-native-community/async-storage": "^1.4.2",
    "@react-native-community/cameraroll": "^1.0.5",
    "@react-native-community/image-editor": "^2.0.0-alpha.0",
    "@react-native-community/netinfo": "^3.2.0",
    "@react-native-community/viewpager": "^1.1.7",
    "aws-amplify": "^1.1.30",
    "axios": "^0.19.0",
    "i18n-js": "^3.2.2",
    "jwt-decode": "^2.2.0",
    "opentok-react-native": "^0.10.3",
    "react": "16.8.3",
    "react-native": "0.59.8",
    "react-native-actionsheet": "^2.4.2",
    "react-native-callkit": "^1.3.4",
    "react-native-camera": "^2.10.2",
    "react-native-device-info": "^2.1.2",
    "react-native-firebase": "^5.5.3",
    "react-native-flags-kit": "^1.0.1",
    "react-native-fs": "^2.13.3",
    "react-native-gesture-handler": "^1.2.2",
    "react-native-keyboard-aware-scroll-view": "^0.8.0",
    "react-native-languages": "^3.0.2",
    "react-native-linear-gradient": "^2.5.4",
    "react-native-md5": "^1.0.0",
    "react-native-permissions": "^1.1.1",
    "react-native-screens": "^1.0.0-alpha.22",
    "react-native-simple-image-cropper": "^1.0.8",
    "react-native-sound": "^0.11.0",
    "react-native-splash-screen": "^3.2.0",
    "react-native-vector-icons": "^6.5.0",
    "react-native-voximplant": "^1.9.0",
    "react-navigation": "^3.11.0",
    "validator": "^11.0.0"
  },
  "devDependencies": {
    "@babel/core": "7.4.5",
    "@babel/runtime": "7.4.5",
    "babel-eslint": "^10.0.1",
    "babel-jest": "24.8.0",
    "babel-plugin-transform-remove-console": "^6.9.4",
    "eslint": "^5.16.0",
    "eslint-plugin-react": "^7.13.0",
    "eslint-plugin-react-native": "^3.7.0",
    "jest": "24.8.0",
    "metro-react-native-babel-preset": "0.54.1",
    "react-native-schemes-manager": "^2.0.0",
    "react-test-renderer": "16.8.3",
    "replace-in-file": "^4.1.1"
  },`

**Comment by YuliaGrigorieva** [comment]
Hello @alexei-sevrukov-topx ,

I suppose that issue is caused by the conflict with `"opentok-react-native": "^0.10.3"`.

Please remove it and let me know the results.

Best regards,
Yulia Grigorieva

**Comment by alexei-sevrukov-topx** [comment]
Thanks @YuliaGrigorieva you were right. I've unkinked opentok and everything is fine.
Is there any solution if I want to use both of this dependencies?

**Comment by YuliaGrigorieva** [comment]
Hello @alexei-sevrukov-topx ,

Unfortunately, I can't provide you any recommendations for this case.
Both modules use the same dependency (probably different versions of this dependency). Changing anything in the installation process or modifying the build process is out of support.

Best regards,
Yulia Grigorieva

**Comment by alexei-sevrukov-topx** [comment]
Thank you very much @YuliaGrigorieva
