### ISSUE TITLE
UI is not updating and waiting for 'establishing connection'. 

### ISSUE THREAD

**Issue by RD1991** [voximplant/react-native-voximplant#9]
Hi There,
UI is stuck at 'establishing connection'. Not able to figure out why it is not getting connected to cloud. Any suggestion ?

**Comment by aylarov** [comment]
Can you get the log from console/logcat ?

**Comment by RD1991** [comment]
Nothing other than 
'
Console was cleared
infoLog.js:17 Running application "VoximplantDemo" with appParams: {"rootTag":1,"initialProps":{}}. __DEV__ === false, development-level warning are OFF, performance optimizations are ON
'

**Comment by RD1991** [comment]
For webSDK I'm receiving following error 

VI WebRTC: 8/29/2016, 5:33:15 PM Media access granted
voximplant.min.js:1 WebSocket connection to 'wss://web-gw-sg-02-30.voximplant.com/platform?version=2&client=chrome&referrer=platform&extra=null&video=false&q=bZTDXJ3oaWBA' failed: Error during WebSocket handshake: Unexpected response code: 501
voximplant.min.js:2 VI WebRTC: 8/29/2016, 5:33:16 PM WS error: [object Event]

**Comment by aylarov** [comment]
Give it a try again please, there was an error in the hostname

**Comment by RD1991** [comment]
Yes, now it works. Thanks a ton @aylarov
