### ISSUE TITLE
[React Native 0.60.0 - React Native Voximplant 1.9.1] Cannot build release apk if compileSdkVersion's 26

### ISSUE THREAD

**Issue by nguyenduythuc** [voximplant/react-native-voximplant#91]
* What went wrong:
Execution failed for task ':react-native-voximplant:verifyReleaseResources'.
> 1 exception was raised by workers:
  com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  /Users/macbook/Documents/react-native/react-native-demo/node_modules/react-native-voximplant/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
  /Users/macbook/Documents/react-native/react-native-demo/node_modules/react-native-voximplant/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
  /Users/macbook/Documents/react-native/react-native-demo/node_modules/react-native-voximplant/android/build/intermediates/res/merged/release/values/values.xml:2738: error: resource android:attr/fontVariationSettings not found.
  /Users/macbook/Documents/react-native/react-native-demo/node_modules/react-native-voximplant/android/build/intermediates/res/merged/release/values/values.xml:2739: error: resource android:attr/ttcIndex not found.
  error: failed linking references.

If i update compileSdkVersion to 28, this error will be solved

**Comment by YuliaGrigorieva** [comment]
Hello @nguyenduythuc ,

Thank you for reporting the issue.

We have just released Voximplant React Native SDK 1.9.2 that contains the fix for this issue.
Please update the sdk in your project.

Best regards,
Yulia Grigorieva
