### ISSUE TITLE
Typescript and strong typing support

### ISSUE THREAD

**Issue by daniily000** [voximplant/react-native-voximplant#92]
Hello, VoxImplant team!

Tried to find any VoxImplant React Native SDK strong typing support, but got nothing. The project where I'm using the SDK is written on Typescript, so I'm curious - is there a way for SDK to support strong typing instead of using 'any' type everywhere? If there is none - do you have some plans to provide VoxImplant typing in future?

Thank you

**Comment by YuliaGrigorieva** [comment]
Hello @daniily000 ,

Thank you for reaching out to us. 

We plan to migrate to TypeScript by October.

Best regards,
Yulia Grigorieva

**Comment by daniily000** [comment]
Thank you for reply, looking forward to meet the migration results!
