### ISSUE TITLE
When app is killed but the foreground service is running call keeps working (awesome!). But if the app is reopened then the call ends

### ISSUE THREAD

**Issue by sanjaypojo** [voximplant/react-native-voximplant#94]
Hi @YuliaGrigorieva, this is a tricky scenario, but it happens with many of our users.

To reproduce this issue,
1. Start a call on android.
2. Once it's connected, background the app.
3. Now kill the app by opening the multi-tasking view and swiping away the app.
4. App is killed but foreground service remains working! Call remains connected (awesome!!)
5. Re-open the app. Call gets killed -- this is what I want to prevent.

Is there any way to prevent it from disconnecting this way?

Thanks,
Sanjay

**Comment by YuliaGrigorieva** [comment]
Hello @sanjaypojo !

Thank you for reporting the issue.

On the step 4, you mention that the call remains connected. Does it mean that the audio is not interrupted and both parties can hear each other?

Best regards,
Yulia Grigorieva

**Comment by sanjaypojo** [comment]
Hi @YuliaGrigorieva, I can confirm that the audio is not interrupted and both parties are able to hear each other!

**Comment by pravinjohn** [comment]
Hi, did you find any solution for this?

**Comment by sanjaypojo** [comment]
@YuliaGrigorieva we've resolved this issue. It was because we were disconnecting from voximplant when the app mounted. We fixed this and everything works now (call remains connected after killing the app and reopening it)
