### ISSUE TITLE
IOS Integration Issue for RN 0.59.6

### ISSUE THREAD

**Issue by jasura44** [voximplant/react-native-voximplant#96]
Hi there, i am trying to integrate VOIXImplant to our existing react native application v 0.59.6 and we are having issues when we are trying to integrate into IOS. Common issue we are having is the RCTEmitter not found. 

Could you advise us if we are not doing something right. 

We followed the integration example.

**Comment by YuliaGrigorieva** [comment]
Hello!

Thank you for reaching out to us.

Could you please provide the exact error description (screenshot or Xcode build output error message)?

The issue may be related to React Native and Xcode 11 compatibility.

Best regards,
Yulia Grigorieva
